
export type EnvironmentKeys =
  | 'ENVIRONMENT_SPECIFIER'
  | 'ENABLE_CONTRACTOR'
  | 'ENABLE_UTILITY_AAA'
  | 'ENABLE_UTILITY_CCC'
  | 'ENABLE_UTILITY_BBB'
  | 'ENABLE_UTILITY_DEMO'
  | 'ENABLE_JOB_REACT'
  | 'ENABLE_JOB_BFF'
  | 'ENABLE_JOB_FACING'
  | 'ENABLE_JOB_REALTIME_MSG_CENTER'
  | 'ENABLE_JOB_TUNNEL'
  | 'ENABLE_JOB_DB_MIGRATION'
  | 'ENABLE_JOB_WEB'
  | 'ENABLE_JOB_MOBILE_API'
  | 'ENABLE_JOB_API'
  | 'ENABLE_JOB_IDENTITYSERVER'
  | 'ENABLE_JOB_AUTH_GATEWAY'
  | 'ENABLE_JOB_SERVICE_DISCOVERY'
  | 'ENABLE_JOB_BACKGROUND_JOB';

